on:
  push:
    branches:
      - master
env:
  ENV: production

jobs:
  Database-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase Project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCOUNT_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.PROD_SUPABASE_PROJECT_ID }}

      - name: Push DB Migrations
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCOUNT_ACCESS_TOKEN }}

  Worker-Deploy:
    name: Worker-Deploy
    needs: Database-Deploy
    defaults:
      run:
        working-directory: ./sprintlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Generate Supabase types
        run: npx supabase gen types --lang=typescript --project-id $SUPABASE_PROJECT_ID > ./db/database.types.ts
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCOUNT_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.PROD_SUPABASE_PROJECT_ID }}

      - name: Generate Drizzle schema
        run: npx drizzle-kit pull --dialect=postgresql --out ./drizzle --url=$SUPABASE_DB_URL
        env:
          SUPABASE_DB_URL: ${{ secrets.PROD_SUPABASE_DB_URL }}

      - name: Delete Existing Worker
        run: npx wrangler delete --env $ENV --force || true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Build & Deploy Worker
        run: npx wrangler deploy --env $ENV
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Set Worker Secrets
        run: |
          printf '%s' "$SUPABASE_URL" | npx wrangler secret put SUPABASE_URL --env $ENV
          printf '%s' "$SUPABASE_ANON_KEY" | npx wrangler secret put SUPABASE_ANON_KEY --env $ENV
          printf '%s' "$JWT_SECRET" | npx wrangler secret put JWT_SECRET --env $ENV
          printf '%s' "$JWT_REFRESH_SECRET" | npx wrangler secret put JWT_REFRESH_SECRET --env $ENV
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY }}
          JWT_SECRET: ${{ secrets.PROD_JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.PROD_JWT_REFRESH_SECRET }}
